# Generated by Django 4.2.3 on 2023-07-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='catFoto',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proFoto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='updated_at',
        ),
    ]
